name: Build and Push Docker image to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Check if it's main branch
        run: |
          if [ $GITHUB_REF != 'refs/heads/main' ]; then
            echo "Not on the main branch, exiting."
            exit 0
          fi
        shell: bash

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./
          push: true
          tags: adimunawar31/adimunawar-betest:latest
